import base from '@repo/lint-config';

const baseConfigs = Array.isArray(base) ? base : [base];

export default [
  {
    ignores: [
      '**/src/generated/**',
      'apps/web/src/routeTree.gen.ts',
      // Generated by `msw init` - vendored service worker, not our code.
      'apps/web/public/mockServiceWorker.js',
      '.agents/**',
      // Agent tooling (skill scripts etc.), not app code.
      '.claude/**',
    ],
  },
  ...baseConfigs,
  {
    // TanStack Router file routes must export the `Route` object from the same
    // file as their component - that is the file-based routing contract - so
    // the react-refresh "only export components" rule cannot hold there.
    files: ['apps/web/src/routes/**/*.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
];
