/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTrashRouteImport } from './routes/_app.trash'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppDataroomsDataroomIdRouteImport } from './routes/_app.datarooms.$dataroomId'
import { Route as AppDataroomsDataroomIdIndexRouteImport } from './routes/_app.datarooms.$dataroomId.index'
import { Route as AppDataroomsDataroomIdFoldersFolderIdRouteImport } from './routes/_app.datarooms.$dataroomId.folders.$folderId'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppDataroomsDataroomIdRoute = AppDataroomsDataroomIdRouteImport.update({
  id: '/datarooms/$dataroomId',
  path: '/datarooms/$dataroomId',
  getParentRoute: () => AppRoute,
} as any)
const AppDataroomsDataroomIdIndexRoute =
  AppDataroomsDataroomIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDataroomsDataroomIdRoute,
  } as any)
const AppDataroomsDataroomIdFoldersFolderIdRoute =
  AppDataroomsDataroomIdFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => AppDataroomsDataroomIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design-system': typeof DesignSystemRoute
  '/favorites': typeof AppFavoritesRoute
  '/trash': typeof AppTrashRoute
  '/datarooms/$dataroomId': typeof AppDataroomsDataroomIdRouteWithChildren
  '/datarooms/$dataroomId/': typeof AppDataroomsDataroomIdIndexRoute
  '/datarooms/$dataroomId/folders/$folderId': typeof AppDataroomsDataroomIdFoldersFolderIdRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/favorites': typeof AppFavoritesRoute
  '/trash': typeof AppTrashRoute
  '/': typeof AppIndexRoute
  '/datarooms/$dataroomId': typeof AppDataroomsDataroomIdIndexRoute
  '/datarooms/$dataroomId/folders/$folderId': typeof AppDataroomsDataroomIdFoldersFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/': typeof AppIndexRoute
  '/_app/datarooms/$dataroomId': typeof AppDataroomsDataroomIdRouteWithChildren
  '/_app/datarooms/$dataroomId/': typeof AppDataroomsDataroomIdIndexRoute
  '/_app/datarooms/$dataroomId/folders/$folderId': typeof AppDataroomsDataroomIdFoldersFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/favorites'
    | '/trash'
    | '/datarooms/$dataroomId'
    | '/datarooms/$dataroomId/'
    | '/datarooms/$dataroomId/folders/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/favorites'
    | '/trash'
    | '/'
    | '/datarooms/$dataroomId'
    | '/datarooms/$dataroomId/folders/$folderId'
  id:
    | '__root__'
    | '/_app'
    | '/design-system'
    | '/_app/favorites'
    | '/_app/trash'
    | '/_app/'
    | '/_app/datarooms/$dataroomId'
    | '/_app/datarooms/$dataroomId/'
    | '/_app/datarooms/$dataroomId/folders/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/datarooms/$dataroomId': {
      id: '/_app/datarooms/$dataroomId'
      path: '/datarooms/$dataroomId'
      fullPath: '/datarooms/$dataroomId'
      preLoaderRoute: typeof AppDataroomsDataroomIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/datarooms/$dataroomId/': {
      id: '/_app/datarooms/$dataroomId/'
      path: '/'
      fullPath: '/datarooms/$dataroomId/'
      preLoaderRoute: typeof AppDataroomsDataroomIdIndexRouteImport
      parentRoute: typeof AppDataroomsDataroomIdRoute
    }
    '/_app/datarooms/$dataroomId/folders/$folderId': {
      id: '/_app/datarooms/$dataroomId/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/datarooms/$dataroomId/folders/$folderId'
      preLoaderRoute: typeof AppDataroomsDataroomIdFoldersFolderIdRouteImport
      parentRoute: typeof AppDataroomsDataroomIdRoute
    }
  }
}

interface AppDataroomsDataroomIdRouteChildren {
  AppDataroomsDataroomIdIndexRoute: typeof AppDataroomsDataroomIdIndexRoute
  AppDataroomsDataroomIdFoldersFolderIdRoute: typeof AppDataroomsDataroomIdFoldersFolderIdRoute
}

const AppDataroomsDataroomIdRouteChildren: AppDataroomsDataroomIdRouteChildren =
  {
    AppDataroomsDataroomIdIndexRoute: AppDataroomsDataroomIdIndexRoute,
    AppDataroomsDataroomIdFoldersFolderIdRoute:
      AppDataroomsDataroomIdFoldersFolderIdRoute,
  }

const AppDataroomsDataroomIdRouteWithChildren =
  AppDataroomsDataroomIdRoute._addFileChildren(
    AppDataroomsDataroomIdRouteChildren,
  )

interface AppRouteChildren {
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppTrashRoute: typeof AppTrashRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDataroomsDataroomIdRoute: typeof AppDataroomsDataroomIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppFavoritesRoute: AppFavoritesRoute,
  AppTrashRoute: AppTrashRoute,
  AppIndexRoute: AppIndexRoute,
  AppDataroomsDataroomIdRoute: AppDataroomsDataroomIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
